[package]
name = "snake-ai"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
macroquad = "0.3"
ndarray = "0.15.6"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.7.0"